import "./globals.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Almacen del Bioquímico",
	description: "Generated by create next app",
	icons: ["/img/logo.png"],
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="es">
			<body className={montserrat.className}>{children}</body>
		</html>
	);
}
